packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": ^24.3.1
  "@types/react-dom": ^19
  "@types/react": ^19.1.12
  next: 15.5.2
  postcss: ^8.5.3
  react-dom: 19.1.1
  react: 19.1.1
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  vitest: ^3.2.4
  zod: ^4.1.5

catalogs:
  design:
    cmdk: ^1.1.1
    date-fns: ^4.1.0
    input-otp: "^1.4.2"
    lucide-react: ^0.542.0
    react-hook-form: ^7.62.0
    recharts: ^2.15.3
    sonner: ^2.0.7
